workflows:
  qsuk-builder:
    name: QSUK APK Builder
    max_build_duration: 30
    environment:
      vars:
        MODULE_PATH: "app"
      groups:
        - qsuk
    scripts:
      - name: Сборка APK
        script: |
          cd $MODULE_PATH
          chmod +x gradlew
          ./gradlew clean assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
